### ISSUE TITLE
Double test runs with abstract test classes

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/AutoTDD#12]
We have a problem with AutoTDD where test cases are run twice on tests that inherit from a class that inherits from testcase but returns true for "isAbstract". We believe this is a bug.

**Comment by MaxiBoether** [comment]
Hi Niklas!

We are currently working on AutoTDD.  Does this problem still occur? Because this seems like a problem in SUnit, not in AutoTDD as AutoTDD is just creating SUnit TestSuites. 

And do I understand the situation right: You've got a TestClass that is run on changes on specific packages, and the tests are ran twice? Or are you saying that you are watching on changes on a testclass? It would be helpful if you could specify (if you still know about this, we know your issue is unfortunately over a year old).

We would be glad if you could still help us improve AutoTDD! Thank you!

**Comment by NiklasKoehnecke** [comment]
Hi,
I wrote that issue more than a year ago, so my memories are not the best anymore.
As far as i remember, the issue was that the number of tests ran by the auto test runner was a lot higher than on the regular test runner. We figured out that for all tests that were a subclass of an abstract class, which itself was a subclass of TestCase, its tests were run twice. (We had project GameMecha, the code is still on github).
However, i do not remember how we configured the auto test runner. 
I managed to recreate this problem on my old image, possibly with an old version of AutoTDD. I tried to run the metacello code to get the new packages and it still behaved the same. However, it only worked after deleting some tests as certain tests just froze the auto test runner (i randomly deleted some and then it at least ran through).

Greetings,
Niklas 
![grafik](https://user-images.githubusercontent.com/24220791/60631909-5eda5180-9e02-11e9-84e1-a406ed217b7b.png)
